### ISSUE TITLE
Install procedure

### ISSUE THREAD

**Issue by franchoco** [niclabs/ratadns-packet-analyzer#3]
The cmake script should define everything to correctly install the software in $PREFIX, install the configuration in /etc, and the daemon scripts in /usr/lib/systemd or /etc/init.d.

**Comment by franchoco** [comment]
ratadns-speedy now is installed in $PREFIX/bin. The daemon scripts may be written in the future (if they are needed). Documentation on how to use this along with Fievel is a MUST now. Closing...

**Comment by madestro** [comment]
Create a new ticket with the new feature, because this issue is ok.
